//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9:00")]
        public string AlarmTime1 {
            get {
                return ((string)(this["AlarmTime1"]));
            }
            set {
                this["AlarmTime1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("上班")]
        public string Remark1 {
            get {
                return ((string)(this["Remark1"]));
            }
            set {
                this["Remark1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12:00")]
        public string AlarmTime2 {
            get {
                return ((string)(this["AlarmTime2"]));
            }
            set {
                this["AlarmTime2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("下班")]
        public string Remark2 {
            get {
                return ((string)(this["Remark2"]));
            }
            set {
                this["Remark2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14:00")]
        public string AlarmTime3 {
            get {
                return ((string)(this["AlarmTime3"]));
            }
            set {
                this["AlarmTime3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("上班")]
        public string Remark3 {
            get {
                return ((string)(this["Remark3"]));
            }
            set {
                this["Remark3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18:00")]
        public string AlarmTime4 {
            get {
                return ((string)(this["AlarmTime4"]));
            }
            set {
                this["AlarmTime4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("下班")]
        public string Remark4 {
            get {
                return ((string)(this["Remark4"]));
            }
            set {
                this["Remark4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Enable1 {
            get {
                return ((bool)(this["Enable1"]));
            }
            set {
                this["Enable1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Enable2 {
            get {
                return ((bool)(this["Enable2"]));
            }
            set {
                this["Enable2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Enable3 {
            get {
                return ((bool)(this["Enable3"]));
            }
            set {
                this["Enable3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Enable4 {
            get {
                return ((bool)(this["Enable4"]));
            }
            set {
                this["Enable4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool[] DayOfWeek1 {
            get {
                return ((bool[])(this["DayOfWeek1"]));
            }
            set {
                this["DayOfWeek1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool[] DayOfWeek2 {
            get {
                return ((bool[])(this["DayOfWeek2"]));
            }
            set {
                this["DayOfWeek2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool[] DayOfWeek3 {
            get {
                return ((bool[])(this["DayOfWeek3"]));
            }
            set {
                this["DayOfWeek3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool[] DayOfWeek4 {
            get {
                return ((bool[])(this["DayOfWeek4"]));
            }
            set {
                this["DayOfWeek4"] = value;
            }
        }
    }
}
